version: '3.8'
services:
  media-downloader:
    build: .
    ports:
      - "5020:5000"
    command: gunicorn -b 0.0.0.0:5000 app:app --timeout 120
    restart: always
    environment:
      - FLASK_ENV=production
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./logs:/app/logs